{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f795882b_81da61b6",
        "filename": "/COMMIT_MSG",
        "patchSetId": 7
      },
      "lineNbr": 9,
      "author": {
        "id": 1000077
      },
      "writtenOn": "2025-03-29T01:27:40Z",
      "side": 1,
      "message": "There\u0027s a small typo in the commit message: \u0027contmuinuously\u0027 should be \u0027continuously\u0027",
      "range": {
        "startLine": 9,
        "startChar": 29,
        "endLine": 9,
        "endChar": 43
      },
      "revId": "cc149ad1955cb11e6138fed22977a86ff82a0327",
      "serverId": "064ee66a-ae46-499d-ad6e-e0a180e6bf4d"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a947c0b8_5f95eb7e",
        "filename": "google/google_api.py",
        "patchSetId": 7
      },
      "lineNbr": 36,
      "author": {
        "id": 1000007
      },
      "writtenOn": "2025-03-28T11:06:47Z",
      "side": 1,
      "message": "This looks very good. But I think the global exception handler can handle it. If possible, could you do me a favor and try throwing a ValueError(MISSING_FIELDS_MSG.format(fields\u003d\u0027, \u0027.join(missing))) to see if the handler can catch it successfully?\n\nThis is code:\nhttps://github.com/Circle-Cat/purrf/blob/main/tools/global_handle_exception/exception_handler.py",
      "revId": "cc149ad1955cb11e6138fed22977a86ff82a0327",
      "serverId": "064ee66a-ae46-499d-ad6e-e0a180e6bf4d"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "24b0e11a_9724e67e",
        "filename": "google/pubsub_subscriber_store.py",
        "patchSetId": 7
      },
      "lineNbr": 105,
      "author": {
        "id": 1000007
      },
      "writtenOn": "2025-03-28T11:06:47Z",
      "side": 1,
      "message": "Iâ€™d like to ask, what is the output of this log statement?",
      "revId": "cc149ad1955cb11e6138fed22977a86ff82a0327",
      "serverId": "064ee66a-ae46-499d-ad6e-e0a180e6bf4d"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f94324a4_599483a1",
        "filename": "google/pubsub_subscriber_store.py",
        "patchSetId": 7
      },
      "lineNbr": 116,
      "author": {
        "id": 1000074
      },
      "writtenOn": "2025-03-31T00:00:13Z",
      "side": 1,
      "message": "It seems that streaming_pull_future.result() will not through timeout error and may block indefinitely, so using streaming_pull_future.result(timeout\u003d60) is a safer option to prevent the listener from getting stuck.",
      "range": {
        "startLine": 110,
        "startChar": 0,
        "endLine": 116,
        "endChar": 38
      },
      "revId": "cc149ad1955cb11e6138fed22977a86ff82a0327",
      "serverId": "064ee66a-ae46-499d-ad6e-e0a180e6bf4d"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "060b67ff_cb9eee3b",
        "filename": "google/pubsub_subscriber_store.py",
        "patchSetId": 7
      },
      "lineNbr": 125,
      "author": {
        "id": 1000007
      },
      "writtenOn": "2025-03-28T11:06:47Z",
      "side": 1,
      "message": "Can you show me an example of this? Because when I did my research, I only found this.\nhttps://developers.google.cn/workspace/events/guides/update-subscription#python_1",
      "revId": "cc149ad1955cb11e6138fed22977a86ff82a0327",
      "serverId": "064ee66a-ae46-499d-ad6e-e0a180e6bf4d"
    }
  ]
}